export const FLIP_FIRST_CARD = 'FLIP_FIRST_CARD';
export const FLIP_SECOND_CARD = 'FLIP_SECOND_CARD';
export const FLIP_FIRST_CARD_BACK = 'FLIP_FIRST_CARD_BACK';
export const FLIP_SECOND_CARD_BACK = 'FLIP_SECOND_CARD_BACK';
export const VANISH_CARDS = 'VANISH_CARDS';
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const SET_CARDS_LIST = 'SET_CARDS_LIST';

export default null;
